services:

  postgres:
    container_name: postgres-sql-sss
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: spring_security_study
    volumes:
      - postgres:/data/postgres
    ports:
      - 5442:5432
    networks:
      - spring-demo
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - 9632:80
    depends_on:
      - postgres
    networks:
      - spring-demo

  mail-dev:
    container_name: mail-dev-sss
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local